name: 'dropbox-github-action'
description: 'Uploads a file to Dropbox'
inputs:
  dropbox-app-key:
    description: 'Dropbox app key'
    required: true
  dropbox-app-secret:
    description: 'Dropbox app secret'
    required: true
  dropbox-refresh-token:
    description: 'Dropbox refresh token'
    required: true
  source-path:
    description: 'Path to the source file'
    required: true
  target-path:
    description: 'Path to the target file in Dropbox'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: get-access-token
      shell: bash
      run: |
        access_token=$(curl -s https://api.dropbox.com/oauth2/token -d refresh_token=${{ inputs.dropbox-refresh-token }} -d grant_type=refresh_token -d client_id=${{ inputs.dropbox-app-key }} -d client_secret=${{ inputs.dropbox-app-secret }} | jq -r '.access_token')
        echo "::add-mask::$access_token"
        echo "access_token=$access_token" >> "$GITHUB_OUTPUT"        
    - id: upload-file
      shell: bash
      run: |
        curl -X POST https://content.dropboxapi.com/2/files/upload \
          --header "Authorization: Bearer ${{ steps.get-access-token.outputs.access_token }}" \
          --header "Dropbox-API-Arg: {\"path\":\"${{ inputs.target-path }}\"}" \
          --header  "Content-Type: application/octet-stream" \
          --data-binary @${{ inputs.source-path }}
        